[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
[build]
target ="/home/mrxie/rust/XHOS/XH_os/x86_64-XH_os.json"
[target.'cfg(target_os = "none")']
runner = "bootimage runner"